name: "Destroy Terraform Infrastructure"

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true
        type: string

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'
    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        working-directory: ./

    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_wif_pool_id: ${{ secrets.WIF_POOL_ID }}


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init  -backend-config="bucket=${{ secrets.TFSTATE_GCS_BUCKET }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
